src/books/urls.py
from django.conf.urls import url
from books import views

urlpatterns = [
    url(r'^$', views.index, name='index'), # 首页
    url(r'books/(?P<books_id>\d+)/$', views.detail, name='detail'), # 详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)/$', views.list, name='list'), # 列表页
]

src/bookstore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('users.urls', namespace='user')), # 用户模块
    url(r'^tinymce/', include('tinymce.urls')), # 富文本编辑器
    url(r'^', include('books.urls', namespace='books')), # 商品模块
    url(r'^cart/', include('cart.urls', namespace='cart')), # 购物车模块
    url(r'^order/', include('order.urls', namespace='order')), # 订单模块
    url(r'^comment/', include('comments.urls', namespace='comment')), # 评论模块
    url(r'^search/', include('haystack.urls')), # 搜索配置
]

src/cart/urls.py
from django.conf.urls import url
from cart import views

urlpatterns = [
    url(r'^add/$', views.cart_add, name='add'), # 添加购物车数据
    url(r'^count/$', views.cart_count, name='count'), # 获取用户购物车中商品的数量
    url(r'^$', views.cart_show, name='show'), # 显示用户的购物车页面
    url(r'^del/$', views.cart_del, name='delete'), # 购物车商品记录删除
    url(r'^update/$', views.cart_update, name='update'), # 更新购物车商品数目
]

src/order/urls.py
from django.conf.urls import url
from order import views

urlpatterns = [
    url(r'^place/$', views.order_place, name='place'), # 订单提交页面
    url(r'^commit/$', views.order_commit, name='commit'), # 生成订单
    url(r'^pay/$', views.order_pay, name='pay'), # 订单支付
    url(r'^check_pay/$', views.check_pay, name='check_pay'), # 查询支付结果
]

src/users/urls.py
from django.conf.urls import url
from users import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'), # 用户注册
    url(r'^register_handle/$', views.register_handle, name='register_handle'), # 用户注册处理
    url(r'^login/$', views.login, name='login'), # 显示登陆页面
    url(r'^login_check/$', views.login_check, name='login_check'), # 用户登录校验
    url(r'^logout/$', views.logout, name='logout'), # 退出用户登录
    url(r'^$', views.user, name='user'), # 用户中心-信息页
    url(r'^address/$', views.address, name='address'), # 用户中心-地址页
    url(r'^order/$', views.order, name='order'), # 用户中心-订单页
    url(r'^verifycode/$', views.verifycode, name='verifycode'), # 验证码功能
    url(r'^active/(?P<token>.*)/$', views.register_active, name='active'), # 用户激活
    url(r'^findpsw/$',views.findpsw,name="findpsw")
]

src/templates/base.html
{# 首页 登录 注册 的父模板 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页顶部标题块 #}
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bulma.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
    {# 网页顶部引入文件块 #}
    {% block topfiles %}
    {% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到西电图灵书城!</div>
            <div class="fr">
                {% if request.session.islogin %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ request.session.username }}</em>
                        <span>|</span>
                        <a href="{% url 'user:logout' %}">退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:user' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:show' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'order:place' %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
{% endblock header_con %}
{# 网页顶部搜索框块 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'books:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"
                                                               style="width: 300px; height: 53px;"></a>
        <div class="search_con fl">
            <form method="get" action="/search/">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
        <div class="guest_cart fr">
            <a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
            <div class="book_count fl" id="show_count">0</div>
        </div>
    </div>
{% endblock search_bar %}
{# 网页主体内容块 #}
{% block body %}{% endblock body %}

<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2018 陕西省西安市长安区 西安电子科技大学 人工智能学院 All Rights Reserved</p>
    <p> 电话：****888 陕ICP备*******号</p>
</div>
{# 获取用户购物车中商品的数目 #}
{% block cart_count %}
    <script>
        $.get('/cart/count/', function (data) {
            // {'res':商品的总数}
            $('#show_count').html(data.res)
        })
    </script>
{% endblock cart_count %}
{# 网页底部html元素块 #}
{% block bottom %}{% endblock bottom %}
{# 网页底部引入文件块 #}
{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>