src/books/urls.py
from django.conf.urls import url
from books import views

urlpatterns = [
    url(r'^$', views.index, name='index'), # 首页
    url(r'books/(?P<books_id>\d+)/$', views.detail, name='detail'), # 详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)/$', views.list, name='list'), # 列表页
]

src/bookstore/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('users.urls', namespace='user')), # 用户模块
    url(r'^tinymce/', include('tinymce.urls')), # 富文本编辑器
    url(r'^', include('books.urls', namespace='books')), # 商品模块
    url(r'^cart/', include('cart.urls', namespace='cart')), # 购物车模块
    url(r'^order/', include('order.urls', namespace='order')), # 订单模块
    url(r'^comment/', include('comments.urls', namespace='comment')), # 评论模块
    url(r'^search/', include('haystack.urls')), # 搜索配置
]

src/cart/urls.py
from django.conf.urls import url
from cart import views

urlpatterns = [
    url(r'^add/$', views.cart_add, name='add'), # 添加购物车数据
    url(r'^count/$', views.cart_count, name='count'), # 获取用户购物车中商品的数量
    url(r'^$', views.cart_show, name='show'), # 显示用户的购物车页面
    url(r'^del/$', views.cart_del, name='delete'), # 购物车商品记录删除
    url(r'^update/$', views.cart_update, name='update'), # 更新购物车商品数目
]

src/users/urls.py
from django.conf.urls import url
from users import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'), # 用户注册
    url(r'^register_handle/$', views.register_handle, name='register_handle'), # 用户注册处理
    url(r'^login/$', views.login, name='login'), # 显示登陆页面
    url(r'^login_check/$', views.login_check, name='login_check'), # 用户登录校验
    url(r'^logout/$', views.logout, name='logout'), # 退出用户登录
    url(r'^$', views.user, name='user'), # 用户中心-信息页
    url(r'^address/$', views.address, name='address'), # 用户中心-地址页
    url(r'^order/$', views.order, name='order'), # 用户中心-订单页
    url(r'^verifycode/$', views.verifycode, name='verifycode'), # 验证码功能
    url(r'^active/(?P<token>.*)/$', views.register_active, name='active'), # 用户激活
    url(r'^findpsw/$',views.findpsw,name="findpsw")
]

src/users/models.py
from django.db import models
from db.base_model import BaseModel
from hashlib import sha1

def get_hash(str):
    '''取一个字符串的hash值'''
    sh = sha1()
    sh.update(str.encode('utf8'))
    return sh.hexdigest()

# Create your models here.
class PassportManager(models.Manager):
    def add_one_passport(self, username, password, email):
        '''添加一个账户信息'''
        passport = self.create(username=username, password=get_hash(password), email=email)
        # 3.返回passport
        return passport

    def get_one_passport(self, username, password):
        '''根据用户名密码查找账户的信息'''
        try:
            passport = self.get(username=username, password=get_hash(password))
        except self.model.DoesNotExist:
            # 账户不存在
            passport = None
        return passport

    def check_passport(self, username):
        '''检查是否存在用户名'''
        try:
            passport = self.get(username=username)
        except self.model.DoesNotExist:
            passport = None
        return passport
        
# Create your models here.
class Passport(BaseModel):
    '''用户模型类'''
    username = models.CharField(max_length=20, verbose_name='用户名称')
    password = models.CharField(max_length=40, verbose_name='用户密码')
    email = models.EmailField(verbose_name='用户邮箱')
    is_active = models.BooleanField(default=False, verbose_name='激活状态')

    objects = PassportManager()

    class Meta:
        db_table = 's_user_account'

class AddressManager(models.Manager):
    '''地址模型管理器类'''
    def get_default_address(self, passport_id):
        '''查询指定用户的默认收货地址'''
        try:
            addr = self.get(passport_id=passport_id, is_default=True)
        except self.model.DoesNotExist:
            # 没有默认收货地址
            addr = None
        return addr

    def add_one_address(self, passport_id, recipient_name, recipient_addr, zip_code, recipient_phone):
        '''添加收货地址'''
        # 判断用户是否有默认收货地址
        addr = self.get_default_address(passport_id=passport_id)

        if addr:
            # 存在默认地址
            is_default = False
        else:
            # 不存在默认地址
            is_default = True

        # 添加一个地址
        addr = self.create(passport_id=passport_id,
                           recipient_name=recipient_name,
                           recipient_addr=recipient_addr,
                           zip_code=zip_code,
                           recipient_phone=recipient_phone,
                           is_default=is_default)
        return addr


class Address(BaseModel):
    '''地址模型类'''
    recipient_name = models.CharField(max_length=20, verbose_name='收件人')
    recipient_addr = models.CharField(max_length=256, verbose_name='收件地址')
    zip_code = models.CharField(max_length=6, verbose_name='邮政编码')
    recipient_phone = models.CharField(max_length=11, verbose_name='联系电话')
    is_default = models.BooleanField(default=False, verbose_name='是否默认')
    passport = models.ForeignKey('Passport', verbose_name='账户')

    objects = AddressManager()

    class Meta:
        db_table = 's_user_address'

src/users/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
import re
from users.models import Passport, Address
from django.http import HttpResponse, JsonResponse
from utils.decorators import login_required
from order.models import OrderInfo, OrderGoods
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous import SignatureExpired
from users.tasks import send_active_email
from django.core.mail import send_mail
from django.conf import settings
import os
from django_redis import get_redis_connection
from books.models import Books
# Create your views here.
def register(request):
    '''显示用户注册页面'''
    return render(request, 'users/register.html')

def register_handle(request):
    '''进行用户注册处理'''
    # 接收数据
    username = request.POST.get('user_name')
    password = request.POST.get('pwd')
    email = request.POST.get('email')

    # 进行数据校验
    if not all([username, password, email]):
        # 有数据为空
        return render(request, 'users/register.html', {'errmsg':'参数不能为空!'})

    # 判断邮箱是否合法
    if not re.match(r'^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$', email):
        # 邮箱不合法
        return render(request, 'users/register.html', {'errmsg':'邮箱不合法!'})

    p = Passport.objects.check_passport(username=username)

    if p:
        return render(request, 'users/register.html', {'errmsg': '用户名已存在！'})

    # 进行业务处理:注册，向账户系统中添加账户
    # Passport.objects.create(username=username, password=password, email=email)
    passport = Passport.objects.add_one_passport(username=username, password=password, email=email)

    # 生成激活的token itsdangerous
    serializer = Serializer(settings.SECRET_KEY, 3600)
    token = serializer.dumps({'confirm':passport.id}) # 返回bytes
    token = token.decode()

    # 给用户的邮箱发激活邮件
    # send_mail('西电图灵书城用户激活', '', settings.EMAIL_FROM, [email], html_message='<a href="http://127.0.0.1:8000/user/active/%s/">http://127.0.0.1:8000/user/active/</a>' % token)
    send_active_email.delay(token, username, email)

    # 注册完，还是返回注册页。
    return redirect(reverse('books:index'))

def login(request):
    '''显示登录页面'''
    username = ''
    checked = ''

    context = {
        'username': username,
        'checked': checked,
    }

    return render(request, 'users/login.html', context)

def findpsw(request):
    """
    用户找回密码页面
    :param request:
    :return:
    """
    return HttpResponse("功能待添加！")

# /user/logout
def logout(request):
    '''用户退出登录'''
    # 清空用户的session信息
    request.session.flush()
    # 跳转到首页
    return redirect(reverse('books:index'))

def login_check(request):
    '''进行用户登录校验'''
    # 1.获取数据
    username = request.POST.get('username')
    password = request.POST.get('password')
    remember = request.POST.get('remember')
    verifycode = request.POST.get('verifycode')

    # 2.数据校验
    if not all([username, password, remember, verifycode]):
        # 有数据为空
        return JsonResponse({'res': 2})

    if verifycode.upper() != request.session['verifycode']:
        return JsonResponse({'res': 2})

    # 3.进行处理:根据用户名和密码查找账户信息
    passport = Passport.objects.get_one_passport(username=username, password=password)

    if passport:
        # 用户名密码正确
        # 获取session中的url_path
        # if request.session.has_key('url_path'):
        #     next_url = request.session.get('url_path')
        # else:
        #     next_url = reverse('books:index')
        next_url = reverse('books:index') # /user/
        jres = JsonResponse({'res': 1, 'next_url': next_url})

        # 判断是否需要记住用户名
        if remember == 'true':
            # 记住用户名
            jres.set_cookie('username', username, max_age=7*24*3600)
        else:
            # 不要记住用户名
            jres.delete_cookie('username')

        # 记住用户的登录状态
        request.session['islogin'] = True
        request.session['username'] = username
        request.session['passport_id'] = passport.id
        return jres
    else:
        # 用户名或密码错误
        return JsonResponse({'res': 0})

@login_required
def user(request):
    '''用户中心-信息页'''
    passport_id = request.session.get('passport_id')
    # 获取用户的基本信息
    addr = Address.objects.get_default_address(passport_id=passport_id)

    # 获取用户的最近浏览信息
    con = get_redis_connection('default')
    key = 'history_%d' % passport_id
    # 取出用户最近浏览的5个商品的id
    history_li = con.lrange(key, 0, 4)
    # history_li = [21,20,11]
    # print(history_li)
    # 查询数据库,获取用户最近浏览的商品信息
    # books_li = Books.objects.filter(id__in=history_li)
    books_li = []
    for id in history_li:
        books = Books.objects.get_books_by_id(books_id=id)
        books_li.append(books)

    return render(request, 'users/user_center_info.html', {'addr': addr,
                                                           'page': 'user',
                                                           'books_li': books_li})

@login_required
def address(request):
    '''用户中心-地址页'''
    # 获取登录用户的id
    passport_id = request.session.get('passport_id')

    if request.method == 'GET':
        # 显示地址页面
        # 查询用户的默认地址
        addr = Address.objects.get_default_address(passport_id=passport_id)
        return render(request, 'users/user_center_site.html', {'addr': addr, 'page': 'address'})
    else:
        # 添加收货地址
        # 1.接收数据
        recipient_name = request.POST.get('username')
        recipient_addr = request.POST.get('addr')
        zip_code = request.POST.get('zip_code')
        recipient_phone = request.POST.get('phone')

        # 2.进行校验
        if not all([recipient_name, recipient_addr, zip_code, recipient_phone]):
            return render(request, 'users/user_center_site.html', {'errmsg': '参数不必为空!'})

        # 3.添加收货地址
        Address.objects.add_one_address(passport_id=passport_id,
                                        recipient_name=recipient_name,
                                        recipient_addr=recipient_addr,
                                        zip_code=zip_code,
                                        recipient_phone=recipient_phone)

        # 4.返回应答
        return redirect(reverse('user:address'))

@login_required
def order(request):
    '''用户中心-订单页'''
    # 查询用户的订单信息
    passport_id = request.session.get('passport_id')

    # 获取订单信息
    order_li = OrderInfo.objects.filter(passport_id=passport_id)

    # 遍历获取订单的商品信息
    # order->OrderInfo实例对象
    for order in order_li:
        # 根据订单id查询订单商品信息
        order_id = order.order_id
        order_books_li = OrderGoods.objects.filter(order_id=order_id)

        # 计算商品的小计
        # order_books ->OrderBooks实例对象
        for order_books in order_books_li:
            count = order_books.count
            price = order_books.price
            amount = count * price
            # 保存订单中每一个商品的小计
            order_books.amount = amount

        # 给order对象动态增加一个属性order_goods_li,保存订单中商品的信息
        order.order_books_li = order_books_li

    context = {
        'order_li': order_li,
        'page': 'order'
    }

    return render(request, 'users/user_center_order.html', context)

from django.http import HttpResponse
def verifycode(request):
    #引入绘图模块
    from PIL import Image, ImageDraw, ImageFont
    #引入随机函数模块
    import random
    #定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(
        20, 100), 255)
    width = 100
    height = 25
    #创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    #创建画笔对象
    draw = ImageDraw.Draw(im)
    #调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    #定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    #随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    #构造字体对象
    font = ImageFont.truetype(os.path.join(settings.BASE_DIR, 'Ubuntu-RI.ttf'), 15)
    #构造字体颜色
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    #绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
    #释放画笔
    del draw
    #存入session，用于做进一步验证
    request.session['verifycode'] = rand_str
    #内存文件操作
    import io
    buf = io.BytesIO()
    #将图片保存在内存中，文件类型为png
    im.save(buf, 'png')
    #将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')

def register_active(request, token):
    '''用户账户激活'''
    serializer = Serializer(settings.SECRET_KEY, 3600)
    try:
        info = serializer.loads(token)
        passport_id = info['confirm']
        # 进行用户激活
        passport = Passport.objects.get(id=passport_id)
        passport.is_active = True
        passport.save()
        # 跳转的登录页
        return redirect(reverse('user:login'))
    except SignatureExpired:
        # 链接过期
        return HttpResponse('激活链接已过期')

src/templates/users/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}西电图灵书城-登录{% endblock title %}
{% block topfiles %}
<script>
    $(function () {
        $('#btnLogin').click(function () {
            // 获取用户名和密码
            username = $('#username').val()
            password = $('#pwd').val()
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            remember = $('input[name="remember"]').prop('checked')
            vc = $('input[name="vc"]').val()
            // 发起ajax请求
            params = {
            	'username': username,
            	'password': password,
                'csrfmiddlewaretoken': csrf,
                'remember': remember,
                'verifycode': vc,
            }
            console.log('params: ', params)
            $.post('/user/login_check/', params, function (data) {
                // 用户名密码错误 {'res':0}
                // 登录成功 {'res':1}
                console.log('data: ', data)
                if (data.res == 0){
                    $('#username').next().html('用户名或密码错误').show()
                }
                else
                {
                    // 跳转页面
                    location.href = data.next_url // /user/
                }
            })
        })
    })
</script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
<body>
	<div class="login_top clearfix">
		<a href="{% url 'books:index' %}" class="login_logo"><img src="{% static 'images/logo.png' %}" style="width: 300px; height: 53px;"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">学AI· 来西电！</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
                    {% csrf_token %}
					<input type="text" id="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
					<div class="user_error">输入错误</div>
					<input type="password" id="pwd" class="pass_input" placeholder="请输入密码">
					<div class="pwd_error">输入错误</div>
					<div style="top: 100px; position: absolute;">
						<input type="text" id="vc" name="vc">
						<img id='verifycode' src="/user/verifycode/" alt="CheckCode"/>
					</div>
					<div class="more_input clearfix">
						<input type="checkbox" name="remember" {{ checked }}>
						<label>记住用户名</label>
						<a href="{% url 'user:findpsw' %}">忘记密码</a>
					</div>
					<input type="button" id="btnLogin" value="登录" class="input_submit">
				</div>
			</div>
		</div>
	</div>
{% endblock body %}
{% block cart_count %}{% endblock cart_count %}

src/templates/users/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}西电图灵书城-注册{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo.png" style="width: 300px; height: 53px;"></a>
			<div class="reg_slogan">学计算机  ·  来西电!</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" action="/user/register_handle/">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”西电图灵书城用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
						{{errmsg}}
					</li>
				</ul>
				</form>
			</div>

		</div>

	</div>
{% endblock body %}
{% block cart_count %}{% endblock cart_count %}

src/templates/users/user_center_info.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}西电图灵书店-首页{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ request.session.username }}</li>
							{% if addr %}
                                <li><span>联系方式：</span>{{ addr.recipient_phone }}</li>
                                <li><span>联系地址：</span>{{ addr.recipient_addr }}</li>
                            {% else %}
                                <li><span>联系方式：</span>无</li>
                                <li><span>联系地址：</span>无</li>
                            {% endif %}
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
				    <ul class="books_type_list clearfix">
				        {% for books in books_li %}
				            <li>
				                <a href="{% url 'books:detail' books_id=books.id %}"><img src="{% static books.image %}"></a>
				                <h4><a href="{% url 'books:detail' books_id=books.id %}">{{ books.name }}</a></h4>
				                <div class="operate">
				                    <span class="prize">￥{{ books.price }}</span>
				                    <span class="unit">{{ books.unite }}</span>
				                    <a href="#" class="add_books" title="加入购物车"></a>
				                </div>
				            </li>
				        {% endfor %}
				    </ul>
				</div>
		</div>
	</div>
{% endblock body %}

src/templates/users/user_center_order.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load filters %}
{% block title %}西电图灵书店-首页{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
                {% csrf_token %}
				<h3 class="common_title2">全部订单</h3>
                {# OrderInfo #}
                {% for order in order_li %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.create_time }}</li>
					<li class="col02">订单号：{{ order.order_id }}</li>
					<li class="col02 stress">{{ order.status }}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {# 遍历出来的order_goods是一个OrderGoods对象 #}
                                {% for order_books in order.order_books_li %}
								<ul class="order_book_list clearfix">					
									<li class="col01"><img src="{% static order_books.books.image %}"></li>
									<li class="col02">{{ order_books.books.name }}<em>{{ order_books.books.price }}元/{{ order_books.books.unit }}</em></li>
									<li class="col03">{{ order_books.count }}</li>
									<li class="col04">{{ order_books.amount }}元</li>
								</ul>
                                {% endfor %}
							</td>
							<td width="15%">
								<span id="list_price"> 
									{{ order.total_price }}元
								</span>
							</td>
							<td width="15%">
								<span id="list_price"> 
									{{ order.status | order_status }}
								</span>
							</td>
							<td width="15%"><a href="#" pay_method="{{ order.pay_method }}" order_id="{{ order.order_id }}" order_status="{{ order.status }}" class="oper_btn">去付款</a></td>
						</span>
						</tr>
					</tbody>
				</table>
                {% endfor %}

				<div class="pagenation">
					<a href="#"><上一页</a>
					<a href="#" class="active">1</a>
					<a href="#">2</a>
					<a href="#">3</a>
					<a href="#">4</a>
					<a href="#">5</a>
					<a href="#">下一页></a>
				</div>
		</div>
	</div>
{% endblock body %}
{% block bottomfiles%}
    <script>
    $(function () {
        $('.oper_btn').click(function () {
            // 获取订单id和订单的状态
            order_id = $(this).attr('order_id')
            order_status = $(this).attr('order_status')
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            params = {'order_id':order_id, 'csrfmiddlewaretoken':csrf}
            if (order_status == 1){
                $.post('/order/pay/', params, function (data) {
                    if (data.res == 3){
                        // 把用户引导支付页面
                        window.open(data.pay_url)
                        // 查询用户的支付结果
                        $.post('/order/check_pay/', params, function (data) {
                            if (data.res == 3){
                                alert('支付成功')
                                // 重新刷新页面
                                location.reload()
                            }
                            else{
                                alert(data.errmsg)
                            }
                        })
                    }
                    else{
                        alert(data.errmsg)
                    }
                })
            }
        })
    })
    </script>
{% endblock bottomfiles %}

src/templates/users/user_center_site.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}西电图灵书店-首页{% endblock title %}
{% block topfiles %}
{% endblock topfiles %}
{% block body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:user' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:order' %}">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
                        {% if addr %}
						    <dd>{{ addr.recipient_addr }} （{{ addr.recipient_name }} 收） {{ addr.recipient_phone }}</dd>
					    {% else %}
                            <dd>无</dd>
                        {% endif %}
                    </dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form method="post" action="/user/address/">
                        {% csrf_token %}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="username">
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="addr"></textarea>
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="zip_code">
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="phone">
						</div>
						<input type="submit" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock body %}